Angela is sitting in the train, commuting to work, when suddenly, the world freezes... Not in the sense of getting cold, but in the sense that the train's movement is completely halted from one moment to the next. At the same time, every passanger in train become inanimate. It's as if someone clicked the pause button, but the world forgot to include Angela in the pause-command.

- (Angela) "I'm dreaming!"
  "Wait... I said that out loud, didn't I?"
  "And I'm allowed to say things out loud, because it's my dream!"
  "I like this... Maybe I should begin thinking out loud more often"
  "Alright, so this is my morning commute, I reckognize that. And, I can see from the progress bars, that we are 5 minutes off Thousand Acre Forest (East), so I have a pretty good idea of the 'where' of this dream"

Angela takes out her cell phone and checks the date on the display: Wednesday - April 10th - 2024. 

- (Angela) "That's today, isn't it?"
  "Uuuh, I remember that guy! I have only ever seen him once on this train"
  "Ok, so the 'when' is today...or yesterday... How the hell do I determine the time OUTSIDE my dream"
- (Brain) "Who cares?"
- (Angela) "Alright... I kinda thought this was my show, but alright"
  "So... Here we are, in a situation I have recently experienced, and you have brought me here..."
  "You've brought me here because I missed something, right?"
  "Because that's what dreams are about... The brain does a complete garbage collection of the heap and cleans out any interrupted and/or unfinished thoughts, and at this point in my day, I left something interrupted"
  "Am I right?"
  "..."
  "Look Brain, I don't negotiate with terrorists... Either you're in the dream, and you ping/pong with me and you get to have your little passive/agressive outbursts, or you're out and you stay out"
  "..."
  "Alright, just remember that you asked for it"
  "DOES A TREE MAKE A SOUND IF IT FALLS IN THE FOREST AND NO-ONE IS AROUND TO HEAR IT?" [shouting]
  "AND WHAT IF IT DOESN'T SO MUCH FALL AS GENTLY LANDS ON IT'S BUTT?"
  "DO TREES EVEN HAVE BUTTS? I KNOW THEY HAVE BUDS, BUT DO THEY HAVE BUTTS?"
  "AND WHAT IF THERE IS SOMEONE AROUND TO HEAR IT, BUT THE PERSON IS DEAF AND..."
- (Brain) "Oh my God, what the hell is wrong with you?"
- (Angela) "Well, if Doctor Petersson couldn't figure that out over the course of 5 years, do you really think we're going to figure it out in this dream?"
- (Brain) "What do you want from me?"
- (Angela) "A simple answer would be nice: Have you brought me here to figure out what I missed?"
- (Brain) "YES!"
- (Angela) "Good! Now, are you in or are you out?"
- (Brain) "I'm OUT! Goodbye"
- (Angela) "Good riddance! I can't stand people - or brains - who think you can have it both ways. Have your cake and eat it too. Now, that gives me an idea..."
  "I will close my eyes, and think about chocolate cake with chocolate frosting..."
  "It worked! But look at that thing, not even in my dreams could I win a bake-off"
  "But... who cares? This one is for science"
  "TONIGHT LADIES AND GENTLEMAN, WE WILL ANSWER THE AGE-OLD QUESTION: 'IF YOU EAT AN ENTIRE CHOCOLATE CAKE IN YOUR DREAMS, WILL YOU WAKE UP AND BE FAT?'"
  "AND... TO HELP US ANSWER THAT QUESTION, HERE IS THE LOVELY AAAAANGEEELLAAAAAA" [clapping]
  "AND NOW... IF THE AUDIENCE WOULD PLEASE SHUT THE FUCK UP AS LOVELY ANGELA ATTEMPTS TO EAT THIS WHOLE CAKE IN ONE GO... Drum-roll please"
  [drum-roll]
  "AND THERE YOU HAVE IT LADIES AND GENTLEMEN, SHE'S DONE IT! LET'S HEAR FROM THE LOVELY ANGELA HOW SHE FEELS"
  "ANGELA! HOW DO YOU FEEL RIGHT NOW?"
  "Well Mike, I feel like I have just swallowed an entire chocolate cake... And I don't even like cake... bu hu... I think I'm going to be sick!"
  "ISN'T SHE JUST A TREAT LADES AND GENTLEMEN!?"
  "WELL, THAT'S IT FOR TONIGHT LADIES AND GENTLEMEN, BE SURE TO CHECK IN AGAIN WHEN WE WAKE UP, TO DISCOVER IF LOVELY ANGELA IS NOW FAT ANGELA. UNTIL NEXT TIME!"
  "..."
  
- (Angela) "Alright, with that out of the way, let's see what we have here"
  "I remember that guy, but why?"
  "Do I feel attracted to him?"
  "No... He's certainly not the type of guy I would usually go for"
  "But this is definitely about him"
  "There was something about what he was doing... and what he was doing was..."
  "He was watching that guy over there. Uff! That guy looks like a complete sleeze bag. Yuck! He's got like a sex-offender vibe to him. I don't want him in my dream"
  "Excuse creep"
- (Creep) "Who me?"
- (Angela) "How many other creeps do you see in this dream?"
- (Creep) "There's at least..."
- (Angela) "That's enough filth out of your filthy mouth. Go stand in the other end of the train where I can't see you"
- (Creep) "Or what?"
- (Angela) "Uuuhh... magic time again"
  "Now, we say abra cadabra, and look what started crawling on your arms... Bull-ants!"
- (Creep) "Eeeew... That's disgusting!"
- (Angela) "Oh yes... It is disgusting, but wait until you feel their bite!"
- (Creep) "AAAAAAAAARRRRRGHHHH! THAT HURTS SO BAD!"
- (Angela) "Yes... That's what I have heard. Now go stand in the other end of the train, and if you leave now, I'll make sure there is someone waiting for you down there with a strong painkiller to ease your troubles"
- (Creep) "ARRRRGGGGGGHHH" [running out of the train car]
- (Angela) "No rest for the wicked! The guy will be waiting for you with a nice shot of fentanyl... Let's hope you the dosis right... Muahaha"
  "Alright... Back to the guy. He was watching the creep, but why?"
  "What do you say we cheat a little Angela...?"
  "Oh my, that's a splendid idea! Seing as this is my dream, and I'm supreme ruler - queen of the bull ants - I could step a little closer and have a better look at the guy"
  "Hmmm... Those are sinister eyes. Pretty color of blue, but they cover some nasty secrets don't they. Intriguing!"
  "Now... You were watching the creep. You weren't in love with the creep, and you don't look like you are about to burst out in a birthday tune for loser, so why were you watching him?"
  "Let me think... Back in the real world... The boring world... The place where I cannot command bull ants... YET (!)... you got off at the same stop as he did, but wait a minute... You went for the exit before he did! Which means, that you must have known where he was going, and when you got off the train... you were going to follow him and... kill him!"
  "That's it, isn't it?! You were following him, and you were following him in order to kill him, and the reason you wanted to kill the creep was... that he's a creep!"
  "... or that is at least what you tell yourself, but maybe that's just an excuse... because you are a very angry man! And so you track down and kill creeps as an outlet for your anger!"
  "Am I right?!"
- (Angry man) "You are right, but I'd like to think I'm also doing some good in the world"
- (Angela) "Holy shit! You talk!"
  "How long have you been there?"
- (Angry man) "Well, the whole time"
- (Angela) "Yeah, but like, there's a lot of people here, but they're not really here... I could draw a moustache on them, and they wouldn't notice"
  "How long have you been... sentient?"
- (Angry man) "It's kinda hard for me to say, but I think the whole time. I was there when you put the Brain in it's right place"
- (Angela) "Oh no... Then you also saw the cake-eating-contest?" [embarrassed]  
- (Angry man) "Yes, I found that bit especially..."
- (Angela) "humiliating?"
- (Angry man) "charming" [smiles]
- (Angela) "Uuuh... I like you!"
  "And forget all the stuff I said about me not being attracted to you - I'm not saying I am or anything - but I was checking to see if you were awake and all"
- (Angry man) "Hey, this is your show... Feel free to change my looks into whatever you prefer" [smiling]
- (Angela) "Hmm... I think we'll stick with it for now... Your look does have kind of a rough quality to it. It's probably just an acquired taste"
- (Angry man) "Have it your way"
- (Angela) "Alright... So I feel like I have solved the first riddle, but I bet there's more... Am I supposed to guess the details of what that creep has done"
- (Angry man) "Oh God no! I've read his file and it's not something I want to be reminded of again"
  "No, for now, you can relax. I have something I need to show you" [get's up and reaches into his pocket]
- (Angela) "Uuuuhhhh... Is this going to be one of those dreams where I'm going to need a long hot shower when I wake up?" [biting her lower lip]
- (Angry man) "That wasn't the plan... Do you want it to be?"
- (Angela) "Hmmmm" [dreamy]
  "Alright... No Alex, let's see what great mystery is hidden behind door number 1. But, before we continue, I need to give you a name... It feels weird thinking of you as 'angry man'"
- (Unnamed man) "Can I be Fernando Sanchez? I like that name"
- (Angela) "No... That you cannot. Because Fernando Sanchez is a silly name, which anybody who's anybody knows..."
  "We'll call you John!"
- (John) "John will do"
- (Angela) "Great... Now, let's see what you have there John"
- (John) "..." [pulls out a cell phone and sits down beside her]
- (Angela) "Can I hold it? It's sort of a thing for me... I like being in control... I know... I'm working on it with Doctor Petersson"
- (John) "I don't mind" [hands the cell phone over]
- (Angela) "You need a new phone! Alright, no time to waste on that now, but let me at least fix the cracks in the screen like...so"
  "Do you want popcorn?"
- (John) "Sure, I could go for popcorn"
- (Angela) "Abra cadabra: POPCORN!"
  "And... We'll hit 'play' like so..."

The cell phone starts playing a movie. The camera fades in on a young man and a young woman sitting in the clearing of a forest on a bright Summers day.
- (Angela) "Uuhh... Is that us?"
- (John) "Not exactly, but to some extend it is"
- (Angela) "Alright... Do you want to be the boy or the girl?"
- (John) "I'd prefer to be the young man"
- (Angela) "Hmmm... Alright... A little boring I suppose... But, you shouldn't ask a question if you're not willing to hear the answer"
  "Uuuh... look... I'm pretty aren't I?"
- (John) "I think so"
- (Angela) "You are kinda handsome too!"
- (John) "On behalf of the young man: thank you. The dialogue is about to start"
- (Angela) "Point taken"

- (Young woman) "They want me to marry him"
- (Young man) "Do you want to marry him?"
- (Young woman) "No! I want to marry you"
- (Young man) "I also want to marry you" [smiling]
- (Young woman) "I don't think it's right that they get to decide"
- (Young man) "It isn't"
- (Young woman) "Is there anything we can do?"
- (Young man) "I think so, but we will have the whole world against us"
- (Young woman) "Well, if the world is ready to go against us for not getting in line with such a stupid demand, I say: 'LET THE WORLD BURN'"
- (Young man) "..." [smiling]
  "I love you, and I think I am always going to love you"
- (Young woman) "I love you, and I want you more than life itself"
  "Will you make love to me?"
- (Young man) "I will"

- (Angela) "The screenplay feels a little cheasy doesn't it?"
- (John) "Yeah, but it's supposed to take place in another day and age"
  "but even so, I'd have to agree with you that it could use a little... spunk"
- (Angela) "Yes... spunk"
  "Uuh, look at them going at it... This isn't PG-13 huh?"
- (John) "You have the phone... You can just press the fast forward"
- (Angela) "No way! Look at that! Look how clumsy they are"
- (John) "I think it's their first time... And this is supposed to be way before porn was a thing"
- (Angela) "Yeah, but this is like the viking age, isn't it? Didn't they have like massive sex orgies and such?"
- (John) "I honestly don't know"
- (Angela) "Uuuhh... I just got to thinking... This was before plumming and regular showers was a thing..."
- (John) "I know what you're driving at... Let's be grateful for modern day hygiene"
- (Angela) "Amen! Alright... I'm just going to fast forward a bit..."
  "Now what do we have here..."
  "Uuuh... there's our young couple again"
  "They look mean! They are up to no good!"
  "Oh... I think I know what's going to happen here... I'm not sure I can watch it"
- (John) "..."
- (Angela) "Alright... Let me at least turn the sound off"
  "Oh, that's horrible! Those people don't stand a chance!"
  "NO! If you touch that child, I'm not going to watch anymore of this!"
- (John) "They don't touch the children. There are a couple of the grown-ups that get spared as well"
- (Angela) "That's good!"
  "How many do they kill?"
- (John) "They sliced the throat of 38 people of the village that night, 35 of which died"
- (Angela) "Because they wanted her to marry someone else?"
- (John) "They were kind of insistent. Those were different times, and she was just a property... He was as well"
- (Angela) "So, no working off the debt of buying her from that jerk that owned her in the kitchen, huh?"
- (John) "I'm afraid not"
- (Angela) "But I bet you didn't come here to show me just that... There's more isn't there"
- (John) "Yes"
- (Angela) "Because the world is not going to just sit back and let them get away with happiness, is it?"
- (John) "And 35 murders + 3 attempted murders in the first degree, but no, it isn't"
- (Angela) "And you want me to watch it, right?"
- (John) "I'm afraid that's best"
- (Angela) "Will you hold me while we watch?"
- (John) "I'd love to"

- (Angela) "NO NO NO NO YOU DUMB BITCH! DON'T GO IN THERE! WHAT'S WRONG WITH YOUR BRAIN? THERE'S ENOUGH SPEARS FOR AN ENTIRE ARMY LEANED AGAINST THE WALL OUTSIDE, AND YOU ARE WILLING TO BELIEVE THERE'S JUST A SINGLE FAMILY IN THERE!!!?!"
- (Angela) "I almost don't feel sorry for you when you are that stupid!"
- (Angela) "Please tell me that the man has a little brains"
  "Yes... that's good... That's right mr. Big Brain, it IS a trap... Yes, just watch them and figure out a plan... Maybe you should jack the spears, eh?"
  "NO! WHAT ARE YOU DOING???! YOU ALREADY KNEW THEY HAD HER! JESUS CHRIST! ALL YOU HAD WAS THE ELEMENT OF SURPRISE AND NOW YOU DON'T EVEN HAVE THAT... ALL BECAUSE THEY WAVED A LITTLE KNIFE AGAINST YOUR GIRLFRIENDS THROAT!"

- (Angela) "Oh no... Please tell me they aren't going to use that for what I think they are going to use it for!"
- (John) "I can't"
- (Angela) "Jeeesus! WHAT THE FUCK IS WRONG WITH MEN???!"
- (John) "I know! But look, it's not just the men"
- (Angela) "Aw hell! I take back what I said about the slaughter in the village! They should have killed ALL OF THEM! Well, not the children... even though they're probably going to grow up to be the same kind of bastards!
- (John) "Without surviving adults, the children would have been as good as dead come Winther"
- (Angela) "Thank you Mister Sinister Realism! Let's do a RomCom next time... I want to see how you handle that!"
- (John) "..." [smiling]
- (Angela) "Wait a minute! What was that?! In the shadows. Let me just pause it... and enlarge... That looks kind of like a man, doesn't it? A really evil man. Is that a man?"
- (John) "The jury is hung on that one... some call him the Shadow-Man and think of him as kind of an orchestrator of these kinds of rituals, some say there isn't anything at all"
- (Angela) "Well, I'm on Team Shadow-Man! There totally was a very evil man right there"
  "Alright, let me just hit 'play' again"
  "Oh, I forgot what this was"
  "How long does this crap go on?"
- (John) "For about an hour"
- (Angela) "Seriously?! What the hell is wrong with people?!"
  "Do I have to watch the whole thing?"
- (John) "No... The highlights are enough"
  "There is a small part of about 5 seconds right before she dies where she looks longingly at the guy with sort of a 'I'll-see-you-on-the-other-side'-look that is really memorable, but I wouldn't advice on watching the entire thing just for that"
- (Angela) "Alright" [handing the cell phone back, and moving to a seat across from John]
  "So. Why did I have to see that?"
- (John) "To get an understanding of what's at stake"
- (Angela) "Cryptic... But I hadn't expected much more to be honest"
  "Is the Shadow-Man real?"
- (John) "I don't know"
- (Angela) "I have a feeling I'm barking up the wrong tree here"
  "There is a riddle in this dream... right here... for me. Right?"
- (John) "I don't know"
- (Angela) "That's right... you are completely oblivious. I mean, not you as you're sitting right here infront of me... But as it played out on the train..."
  "You were sitting in the train... Closing in on the prey... And your entire focus was on that!"
  "And it wasn't supposed to be"
  "You were supposed to notice me!"
- (John) "I'm not sure there is any 'supposed' here... that would imply predetermination"
- (Angela) "Potato, potarto... But I get it... Something else could have happened here... And in almost any other circumstance, it would have, but you were too focused on that creep to play the part right"
  "UGH! I'm going to BURN that creep!"

Angela closes her eyes and looks concentrated, when suddenly a loud scream is heard from the other end of the train.

- (John) "..." [smiling, while fading away]
- (Angela) "John! Where are you going? John!"

The entirity of Angela's dream world desolves into nothing, and Angela is gripped by the feeling of falling through endless darkness.
Angela wakes up in chok! And as it turns out, she did have to take a shower when she woke up, but that was from being drenched in sweat. 
She had not gotten fat.